site_name: NiTiSCore Wiki
site_author: NiTiS-Dev
site_description: Official Wiki of NiTiSCore libraries
site_url: https://nitis-dev.github.io/NiTiSLibsWiki/

repo_name: NiTiSCore Wiki
repo_url: https://github.com/NiTiS-Dev/NiTiSLibsWiki

edit_uri: "https://github.com/NiTiS-Dev/NiTiSLibsWiki/edit/"

copyright: Copyright &copy; 2022 NiTiS-Dev

plugins:
  - git-revision-date

theme:
  name: material
  repo: material/github
  logo: images/nitis-core-icon.svg
  favicon: images/nitis-core-icon.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
      primary: blue gray
      accent: deep purple
    - media: "(prefers-color-scheme: dark)"
      scheme: dark-mode
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
      primary: red
      accent: red
  features:
  - navigation.tracking
  - navigation.instant
  - content.tabs.link
  - search.hightlight
  
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
