name: Generate Docks

on:
  push:
    branches:
    - "singleton"
    
  schedule:
  - cron: "30 4 * * *"
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Python v3
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Python Update
      run: |
        python3 -m pip install --upgrade pip
  
