name: Generate Docks

on:
  push:
    branches:
    - "singleton"
    
  schedule:
  - cron: "30 4 1 *2 *"
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Python v3
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Python Update
      run: |
        python3 -m pip install --upgrade pip
    - name: Install DotNet v6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.x'
    - name: Install Python Required Modules
      run: python3 -m pip install -r ./requirements.txt
    - name: Run Pages Generator
      run: |
        dotnet run Generator\*.csproj -c Release --no-logo
    - name: Generate docs
      run: |
        mkdocs build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
  
